### ISSUE TITLE
Ask for update

### ISSUE THREAD

**Issue by huynq55** [nguyenpham/FelicityEgtb#2]
Looks like the project has stopped. Will there be any updates in the near future? It would be nice if you could public the generator tool.

**Comment by nguyenpham** [comment]
It is not really stopped since someone has been using the generator to generate huge data.

I have been considering publishing the code of the generator but it is required cleaning first (some code is so ugly because of being fast developing).

BTW, I have planned to create a totally new open-source generator for both Xiangqi and Chess and with much more flexibility, say, select between DTM, DTC, compress algorithms... and easier to understand/maintement. However, it requires a lot of labor and intensive work thus I will start later.

**Comment by nguyenpham** [comment]
We have been working on a total new code
